import { StyleSheet } from 'react-native';
import { HEIGHT, WIDTH } from '../../constants/config';
import { RFValue } from 'react-native-responsive-fontsize';
import { darkTheme, spacing, radius, typography } from '../../theme';

// Factory – call with the active theme to get fully themed styles
export const makeHomeStyles = theme => {
  const c = theme.colors;
  const sh = theme.shadows;

  return StyleSheet.create({
    safeareacontainer: {
      flex: 1,
      backgroundColor: 'transparent',
    },
    parkingIcon: {
      width: 50,
      height: 50,
      borderWidth: 3,
      borderRadius: radius.sm,
      justifyContent: 'center',
      alignItems: 'center',
    },
    parkingText: {
      fontSize: typography.xxl,
      fontWeight: typography.bold,
      color: c.white,
    },
    listContainer: {
      paddingHorizontal: spacing.lg,
      paddingBottom: spacing.xxl,
    },
    headerText: {
      fontSize: typography.lg,
      fontWeight: typography.semibold,
      marginBottom: spacing.md,
      color: c.text,
      marginLeft: spacing.sm,
    },
    summaryCard: {
      padding: spacing.lg,
      backgroundColor: c.cardBg,
      borderRadius: radius.xl,
      marginBottom: spacing.md,
      marginTop: spacing.lg,
      width: WIDTH * 0.9,
      alignSelf: 'center',
      borderWidth: 1.5,
      borderColor: c.cardBorder,
      ...sh.glow,
    },
    pieRowContainer: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      alignItems: 'center',
    },
    pieContainer: { width: '50%' },
    legendContainer: {
      width: '45%',
      bottom: 50,
      right: spacing.sm,
      padding: spacing.md,
      backgroundColor: 'transparent',
      borderRadius: radius.sm,
      ...sh.sm,
    },
    summaryItem: {
      flexDirection: 'row',
      alignItems: 'center',
      marginVertical: spacing.xxs,
    },
    statusDot: {
      width: 10,
      height: 10,
      borderRadius: 5,
      marginRight: spacing.sm,
    },
    summaryLabel: {
      fontSize: RFValue(typography.sm),
      color: c.textSecondary,
      flex: 1,
    },
    summaryValue: {
      fontSize: RFValue(typography.sm),
      color: c.text,
      fontWeight: typography.semibold,
    },
    cardContainer: {
      height: HEIGHT * 0.35,
      borderRadius: radius.xl,
      overflow: 'hidden',
      marginBottom: spacing.lg,
      backgroundColor: c.cardBg,
      borderWidth: 1,
      borderColor: c.cardBorder,
      ...sh.md,
    },
    backgroundImage: {
      width: '100%',
      height: '100%',
      justifyContent: 'flex-start',
    },
    imageStyle: {
      resizeMode: 'cover',
      opacity: 0.2,
    },
    overlay: {
      ...StyleSheet.absoluteFillObject,
      backgroundColor: 'rgba(255, 255, 255, 0.07)',
    },
    cardContent: { padding: spacing.lg },
    cardHeader: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      alignItems: 'center',
      paddingHorizontal: spacing.md,
      paddingVertical: spacing.sm,
      backgroundColor: 'transparent',
      borderBottomWidth: StyleSheet.hairlineWidth,
      borderColor: c.border,
    },
    cardTitle: {
      fontSize: typography.lg,
      fontWeight: typography.semibold,
      color: c.text,
    },
    filterIcon: { width: 22, height: 22, tintColor: c.textMuted },
    dateButtons: {
      flexDirection: 'column',
      alignItems: 'flex-end',
      gap: spacing.xs,
    },
    dateButton: {
      width: '100%',
      backgroundColor: c.inputBg,
      padding: spacing.sm,
      borderRadius: radius.sm,
      marginBottom: spacing.xs,
      borderWidth: 1,
      borderColor: c.inputBorder,
    },
    dateButtonText: {
      fontSize: RFValue(typography.sm),
      color: c.text,
      textAlign: 'center',
      fontWeight: typography.bold,
    },
    calendarContainer: { marginTop: spacing.sm },
    calendar: { marginTop: -100 },
    watermarkIcon: {
      position: 'absolute',
      bottom: spacing.sm,
      right: spacing.sm,
      opacity: 0.2,
    },
    overSpeedDetails: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      alignItems: 'center',
      height: HEIGHT * 0.2,
      paddingTop: 50,
      backgroundColor: c.errorLight,
      borderRadius: radius.sm,
      width: '100%',
    },
    detailBox: {
      marginHorizontal: spacing.xxs,
      padding: spacing.sm,
      backgroundColor: c.surface,
      borderRadius: radius.sm,
      alignItems: 'center',
      borderWidth: 1,
      borderColor: c.border,
      ...sh.md,
    },
    detailLabel: {
      fontSize: RFValue(typography.xs),
      color: c.textMuted,
      marginBottom: spacing.xxs,
      fontWeight: typography.medium,
    },
    detailValue: {
      fontSize: RFValue(typography.md),
      color: c.error,
      fontWeight: typography.bold,
    },
    idleDetails: {
      height: HEIGHT * 0.2,
      paddingTop: 50,
      flexDirection: 'row',
      justifyContent: 'space-between',
      alignItems: 'center',
      backgroundColor: c.infoLight,
      borderRadius: radius.sm,
      width: '100%',
    },
    idleBox: {
      flex: 1,
      marginHorizontal: spacing.xxs,
      padding: spacing.sm,
      backgroundColor: c.surface,
      borderRadius: radius.md,
      alignItems: 'center',
      borderWidth: 1,
      borderColor: c.border,
      ...sh.md,
    },
    iconTextRow: {
      flexDirection: 'row',
      alignItems: 'center',
      marginBottom: spacing.xxs,
    },
    idleLabel: {
      fontSize: RFValue(typography.sm),
      color: c.textMuted,
      fontWeight: typography.medium,
      marginLeft: spacing.xxs,
    },
    idleValue: {
      fontSize: RFValue(typography.md),
      color: c.info,
      fontWeight: typography.bold,
    },
    fuelDetails: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      alignItems: 'center',
      height: HEIGHT * 0.2,
      paddingTop: 50,
      backgroundColor: c.successLight,
      borderRadius: radius.sm,
      width: '100%',
    },
    fuelBox: {
      flex: 1,
      marginHorizontal: spacing.xxs,
      padding: spacing.sm,
      backgroundColor: c.surface,
      borderRadius: radius.md,
      alignItems: 'center',
      borderWidth: 1,
      borderColor: c.border,
      ...sh.md,
    },
    fuelLabel: {
      fontSize: RFValue(typography.sm),
      color: c.textMuted,
      fontWeight: typography.medium,
      marginLeft: spacing.xxs,
    },
    fuelValue: {
      fontSize: RFValue(typography.md),
      fontWeight: typography.bold,
      color: c.success,
    },
    zoneDetails: {
      height: HEIGHT * 0.2,
      paddingTop: 50,
      backgroundColor: c.infoLight,
      borderRadius: radius.sm,
      width: '100%',
      flexDirection: 'row',
      justifyContent: 'space-between',
      alignItems: 'center',
    },
    zoneContent: { flexDirection: 'row', alignItems: 'center' },
    zoneTextBox: { marginLeft: spacing.sm },
    zoneLabel: {
      fontSize: RFValue(typography.sm),
      color: c.textMuted,
      fontWeight: typography.medium,
    },
    zoneValue: {
      fontSize: RFValue(typography.md),
      fontWeight: typography.bold,
      color: c.primary,
    },
    timelineDeviation: {
      height: HEIGHT * 0.2,
      width: '100%',
      backgroundColor: c.warningLight,
      borderRadius: radius.sm,
      padding: spacing.sm,
      justifyContent: 'space-around',
      marginBottom: 100,
    },
    StayZone: {
      height: HEIGHT * 0.2,
      width: '100%',
      backgroundColor: c.surface,
      borderRadius: radius.sm,
      padding: spacing.sm,
      justifyContent: 'space-around',
      marginBottom: 100,
    },
    StayAwayZone: {
      height: HEIGHT * 0.2,
      width: '100%',
      backgroundColor: c.errorLight,
      borderRadius: radius.sm,
      padding: spacing.sm,
      justifyContent: 'space-around',
      marginBottom: 100,
    },
    ObjectAlerts: {
      height: HEIGHT * 0.23,
      width: '100%',
      backgroundColor: c.successLight,
      borderRadius: radius.sm,
      padding: spacing.sm,
      justifyContent: 'space-around',
      marginBottom: 100,
    },
    timelineItem: {
      flexDirection: 'row',
      alignItems: 'center',
      marginBottom: spacing.sm,
    },
    timelineTextBox: { marginLeft: spacing.sm },
    timelineLabel: {
      fontSize: RFValue(typography.base),
      color: c.text,
      fontWeight: typography.semibold,
    },
    timelineValue: {
      fontSize: RFValue(typography.sm),
      color: c.warning,
      marginTop: spacing.xxs,
    },
    modalOverlay: {
      flex: 1,
      backgroundColor: 'rgba(0,0,0,0.55)',
      justifyContent: 'center',
      alignItems: 'center',
    },
    modalContainer: {
      width: '85%',
      maxWidth: 360,
      backgroundColor: c.surfaceElevated,
      padding: spacing.xl,
      borderRadius: radius.xl,
      borderWidth: 1,
      borderColor: c.border,
      ...sh.glow,
    },
    modalTitle: {
      fontSize: typography.xl,
      fontWeight: typography.semibold,
      marginBottom: spacing.lg,
      textAlign: 'center',
      color: c.text,
    },
    label: {
      fontSize: typography.md,
      fontWeight: typography.semibold,
      marginTop: spacing.sm,
      marginBottom: spacing.xxs,
      color: c.text,
    },
    optionRow: {
      flexDirection: 'row',
      justifyContent: 'space-around',
      marginBottom: spacing.sm,
    },
    optionButton: {
      paddingVertical: spacing.xs,
      paddingHorizontal: spacing.md,
      backgroundColor: c.surface,
      borderRadius: radius.xs,
    },
    optionButtonSelected: {
      backgroundColor: c.primaryLight,
      borderWidth: 1,
      borderColor: c.primary,
    },
    statusCardsContainer: {
      flex: 1,
      justifyContent: 'space-between',
    },
    statusCard: {
      backgroundColor: c.surface,
      borderRadius: radius.sm,
      padding: spacing.sm,
      marginTop: spacing.xs,
      borderLeftWidth: 3,
      borderLeftColor: c.primary,
      ...sh.sm,
    },
    statusTitle: {
      fontSize: RFValue(9),
      color: c.textSecondary,
      fontWeight: typography.semibold,
    },
    statusCount: {
      fontSize: RFValue(11),
      fontWeight: typography.bold,
      color: c.text,
    },
    modalOverlayPie: {
      flex: 1,
      backgroundColor: 'rgba(0,0,0,0.55)',
      justifyContent: 'center',
      alignItems: 'center',
    },
    modalContentPie: {
      width: '80%',
      backgroundColor: c.surfaceElevated,
      borderRadius: radius.md,
      padding: spacing.lg,
      alignItems: 'center',
      ...sh.lg,
    },
    modalHeaderPie: {
      fontSize: typography.xl,
      fontWeight: typography.bold,
      color: c.primary,
    },
    modalCloseButtonPie: {
      marginTop: spacing.lg,
      backgroundColor: c.primary,
      paddingVertical: spacing.sm,
      paddingHorizontal: spacing.lg,
      borderRadius: radius.xs,
    },
    modalCloseTextPie: {
      color: c.white,
      fontSize: typography.md,
    },
    tableContainer: {
      marginHorizontal: spacing.lg,
      borderRadius: radius.sm,
      overflow: 'hidden',
      backgroundColor: c.surface,
      ...sh.sm,
    },
    tableHeader: {
      flexDirection: 'row',
      backgroundColor: c.cardBg,
      paddingVertical: spacing.md,
      paddingHorizontal: spacing.sm,
    },
    tableHeaderCell: {
      flex: 1,
      fontWeight: typography.semibold,
      color: c.text,
      fontSize: RFValue(typography.sm),
    },
    tableRow: {
      flexDirection: 'row',
      paddingVertical: spacing.xs,
      paddingHorizontal: spacing.xs,
      borderTopWidth: 1,
      borderColor: c.border,
      backgroundColor: 'transparent',
    },
    tableCell: {
      flex: 1,
      color: c.textSecondary,
      fontSize: RFValue(typography.sm),
    },
  });
};

// Legacy export (dark) – keeps existing `import { styles }` working
export const styles = makeHomeStyles(darkTheme);
