import { StyleSheet } from 'react-native';
import { HEIGHT, WIDTH } from '../../constants/config';
import { RFValue } from 'react-native-responsive-fontsize';
import { colors, spacing, radius, shadows, typography } from '../../theme';

export const styles = StyleSheet.create({
  safeareacontainer: {
    flex: 1,
    backgroundColor: colors.background,
  },
  parkingIcon: {
    width: 50,
    height: 50,
    borderWidth: 3,
    borderRadius: radius.sm,
    justifyContent: 'center',
    alignItems: 'center',
  },
  parkingText: {
    fontSize: typography.xxl,
    fontWeight: typography.bold,
    color: colors.white,
  },
  listContainer: {
    paddingHorizontal: spacing.lg,
    paddingBottom: spacing.xxl,
  },
  headerText: {
    fontSize: typography.lg,
    fontWeight: typography.semibold,
    marginBottom: spacing.md,
    color: colors.text,
    marginLeft: spacing.sm,
  },
  summaryCard: {
    padding: spacing.lg,
    backgroundColor: colors.surface,
    borderRadius: radius.lg,
    marginBottom: spacing.md,
    marginTop: spacing.lg,
    width: WIDTH * 0.9,
    alignSelf: 'center',
    ...shadows.sm,
  },
  pieRowContainer: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  pieContainer: {
    width: '50%',
  },
  legendContainer: {
    width: '45%',
    bottom: 50,
    right: spacing.sm,
    padding: spacing.md,
    backgroundColor: colors.surface,
    borderRadius: radius.sm,
    ...shadows.sm,
  },
  summaryItem: {
    flexDirection: 'row',
    alignItems: 'center',
    marginVertical: spacing.xxs,
  },
  statusDot: {
    width: 10,
    height: 10,
    borderRadius: 5,
    marginRight: spacing.sm,
  },
  summaryLabel: {
    fontSize: RFValue(typography.sm),
    color: colors.textSecondary,
    flex: 1,
  },
  summaryValue: {
    fontSize: RFValue(typography.sm),
    color: colors.text,
    fontWeight: typography.semibold,
  },
  cardContainer: {
    height: HEIGHT * 0.35,
    borderRadius: radius.lg,
    overflow: 'hidden',
    marginBottom: spacing.lg,
    backgroundColor: colors.surface,
    ...shadows.sm,
  },
  backgroundImage: {
    width: '100%',
    height: '100%',
    justifyContent: 'flex-start',
  },
  imageStyle: {
    resizeMode: 'cover',
    opacity: 0.2,
  },
  overlay: {
    ...StyleSheet.absoluteFillObject,
    backgroundColor: 'rgba(255,255,255,0.35)',
  },
  cardContent: {
    padding: spacing.lg,
  },
  cardHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingHorizontal: spacing.lg,
    paddingVertical: spacing.md,
    backgroundColor: 'transparent',
    borderBottomWidth: StyleSheet.hairlineWidth,
    borderColor: colors.border,
  },
  cardTitle: {
    fontSize: typography.lg,
    fontWeight: typography.semibold,
    color: colors.text,
  },
  filterIcon: {
    width: 22,
    height: 22,
    tintColor: colors.textMuted,
  },
  dateButtons: {
    flexDirection: 'column',
    alignItems: 'flex-end',
    gap: spacing.xs,
  },
  dateButton: {
    width: '100%',
    backgroundColor: colors.borderLight,
    padding: spacing.xxs,
    borderRadius: radius.xs,
    marginBottom: spacing.xxs,
  },
  dateButtonText: {
    fontSize: RFValue(typography.xs),
    color: colors.textSecondary,
    textAlign: 'center',
  },
  calendarContainer: {
    marginTop: spacing.sm,
  },
  calendar: {
    marginTop: -100,
  },
  watermarkIcon: {
    position: 'absolute',
    bottom: spacing.sm,
    right: spacing.sm,
    opacity: 0.2,
  },
  overSpeedDetails: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    height: HEIGHT * 0.2,
    paddingTop: 50,
    backgroundColor: colors.errorLight,
    borderRadius: radius.sm,
    width: '100%',
  },
  detailBox: {
    marginHorizontal: spacing.xxs,
    padding: spacing.sm,
    backgroundColor: colors.surface,
    borderRadius: radius.sm,
    alignItems: 'center',
    ...shadows.sm,
  },
  detailLabel: {
    fontSize: RFValue(typography.xs),
    color: colors.textMuted,
    marginBottom: spacing.xxs,
    fontWeight: typography.medium,
  },
  detailValue: {
    fontSize: RFValue(typography.md),
    color: colors.error,
    fontWeight: typography.bold,
  },
  idleDetails: {
    height: HEIGHT * 0.2,
    paddingTop: 50,
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    backgroundColor: colors.infoLight,
    borderRadius: radius.sm,
    width: '100%',
  },
  idleBox: {
    flex: 1,
    marginHorizontal: spacing.xxs,
    padding: spacing.sm,
    backgroundColor: colors.surface,
    borderRadius: radius.sm,
    alignItems: 'center',
    ...shadows.sm,
  },
  iconTextRow: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: spacing.xxs,
  },
  idleLabel: {
    fontSize: RFValue(typography.sm),
    color: colors.textMuted,
    fontWeight: typography.medium,
    marginLeft: spacing.xxs,
  },
  idleValue: {
    fontSize: RFValue(typography.md),
    color: colors.info,
    fontWeight: typography.bold,
  },
  fuelDetails: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    height: HEIGHT * 0.2,
    paddingTop: 50,
    backgroundColor: colors.successLight,
    borderRadius: radius.sm,
    width: '100%',
  },
  fuelBox: {
    flex: 1,
    marginHorizontal: spacing.xxs,
    padding: spacing.sm,
    backgroundColor: colors.surface,
    borderRadius: radius.sm,
    alignItems: 'center',
    ...shadows.sm,
  },
  fuelLabel: {
    fontSize: RFValue(typography.sm),
    color: colors.textMuted,
    fontWeight: typography.medium,
    marginLeft: spacing.xxs,
  },
  fuelValue: {
    fontSize: RFValue(typography.md),
    fontWeight: typography.bold,
    color: colors.success,
  },
  zoneDetails: {
    height: HEIGHT * 0.2,
    paddingTop: 50,
    backgroundColor: colors.infoLight,
    borderRadius: radius.sm,
    width: '100%',
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  zoneContent: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  zoneTextBox: {
    marginLeft: spacing.sm,
  },
  zoneLabel: {
    fontSize: RFValue(typography.sm),
    color: colors.textMuted,
    fontWeight: typography.medium,
  },
  zoneValue: {
    fontSize: RFValue(typography.md),
    fontWeight: typography.bold,
    color: colors.primary,
  },
  timelineDeviation: {
    height: HEIGHT * 0.2,
    width: '100%',
    backgroundColor: colors.warningLight,
    borderRadius: radius.sm,
    padding: spacing.sm,
    justifyContent: 'space-around',
    marginBottom: 100,
  },
  StayZone: {
    height: HEIGHT * 0.2,
    width: '100%',
    backgroundColor: 'rgba(200, 141, 210, 0.12)',
    borderRadius: radius.sm,
    padding: spacing.sm,
    justifyContent: 'space-around',
    marginBottom: 100,
  },
  StayAwayZone: {
    height: HEIGHT * 0.2,
    width: '100%',
    backgroundColor: colors.errorLight,
    borderRadius: radius.sm,
    padding: spacing.sm,
    justifyContent: 'space-around',
    marginBottom: 100,
  },
  ObjectAlerts: {
    height: HEIGHT * 0.23,
    width: '100%',
    backgroundColor: colors.successLight,
    borderRadius: radius.sm,
    padding: spacing.sm,
    justifyContent: 'space-around',
    marginBottom: 100,
  },
  timelineItem: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: spacing.sm,
  },
  timelineTextBox: {
    marginLeft: spacing.sm,
  },
  timelineLabel: {
    fontSize: RFValue(typography.base),
    color: colors.text,
    fontWeight: typography.semibold,
  },
  timelineValue: {
    fontSize: RFValue(typography.sm),
    color: colors.warning,
    marginTop: spacing.xxs,
  },
  modalOverlay: {
    flex: 1,
    backgroundColor: 'rgba(0,0,0,0.5)',
    justifyContent: 'center',
    alignItems: 'center',
  },
  modalContainer: {
    width: '85%',
    maxWidth: 360,
    backgroundColor: colors.surface,
    padding: spacing.xl,
    borderRadius: radius.lg,
    ...shadows.lg,
  },
  modalTitle: {
    fontSize: typography.xl,
    fontWeight: typography.semibold,
    marginBottom: spacing.lg,
    textAlign: 'center',
    color: colors.text,
  },
  label: {
    fontSize: typography.md,
    fontWeight: typography.semibold,
    marginTop: spacing.sm,
    marginBottom: spacing.xxs,
    color: colors.text,
  },
  optionRow: {
    flexDirection: 'row',
    justifyContent: 'space-around',
    marginBottom: spacing.sm,
  },
  optionButton: {
    paddingVertical: spacing.xs,
    paddingHorizontal: spacing.md,
    backgroundColor: colors.borderLight,
    borderRadius: radius.xs,
  },
  optionButtonSelected: {
    backgroundColor: colors.infoLight,
  },
  dateButton: {
    backgroundColor: colors.primary,
    padding: spacing.sm,
    borderRadius: radius.xs,
    marginVertical: spacing.xs,
    alignItems: 'center',
  },
  dateButtonText: {
    color: colors.white,
    fontSize: RFValue(typography.sm),
  },
  statusCardsContainer: {
    flex: 1,
    justifyContent: 'space-between',
  },
  statusCard: {
    backgroundColor: colors.surface,
    borderRadius: radius.sm,
    padding: spacing.sm,
    marginTop: spacing.xs,
    borderLeftWidth: 3,
    borderLeftColor: colors.primary,
    ...shadows.sm,
  },
  statusTitle: {
    fontSize: RFValue(9),
    color: colors.textSecondary,
    fontWeight: typography.semibold,
  },
  statusCount: {
    fontSize: RFValue(11),
    fontWeight: typography.bold,
    color: colors.text,
  },
  modalOverlayPie: {
    flex: 1,
    backgroundColor: 'rgba(0,0,0,0.5)',
    justifyContent: 'center',
    alignItems: 'center',
  },
  modalContentPie: {
    width: '80%',
    backgroundColor: colors.surface,
    borderRadius: radius.md,
    padding: spacing.lg,
    alignItems: 'center',
    ...shadows.lg,
  },
  modalHeaderPie: {
    fontSize: typography.xl,
    fontWeight: typography.bold,
    color: colors.primary,
  },
  modalCloseButtonPie: {
    marginTop: spacing.lg,
    backgroundColor: colors.primary,
    paddingVertical: spacing.sm,
    paddingHorizontal: spacing.lg,
    borderRadius: radius.xs,
  },
  modalCloseTextPie: {
    color: colors.white,
    fontSize: typography.md,
  },
  tableContainer: {
    marginHorizontal: spacing.lg,
    borderRadius: radius.sm,
    overflow: 'hidden',
    backgroundColor: colors.surface,
    ...shadows.sm,
  },
  tableHeader: {
    flexDirection: 'row',
    backgroundColor: colors.borderLight,
    paddingVertical: spacing.md,
    paddingHorizontal: spacing.sm,
  },
  tableHeaderCell: {
    flex: 1,
    fontWeight: typography.semibold,
    color: colors.text,
    fontSize: RFValue(typography.sm),
  },
  tableRow: {
    flexDirection: 'row',
    paddingVertical: spacing.xs,
    paddingHorizontal: spacing.xs,
    borderTopWidth: 1,
    borderColor: colors.border,
    backgroundColor: 'transparent',
  },
  tableCell: {
    flex: 1,
    color: colors.textSecondary,
    fontSize: RFValue(typography.sm),
  },
});
